---
driver:
  name: docker
  use_sudo: false
  privileged: true

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  hosts: all
  roles_path: ../ansible-os-hardening/
  playbook: default.yml
  ansible_extra_flags:
    - "--skip-tags=sysctl"

platforms:
- name: centos6-ansible-latest
  driver:
    image: rndmh3ro/docker-centos6-ansible:latest
    platform: centos
- name: centos6-ansible-19
  driver:
    image: rndmh3ro/docker-centos6-ansible:1.9
    platform: centos
- name: centos7-ansible-latest
  driver:
    image: rndmh3ro/docker-centos7-ansible:latest
    platform: centos
- name: centos7-ansible-19
  driver:
    image: rndmh3ro/docker-centos7-ansible:1.9
    platform: centos
- name: oracle6-ansible-latest
  driver:
    image: rndmh3ro/docker-oracle6-ansible:latest
    platform: centos
- name: oracle6-ansible-19
  driver:
    image: rndmh3ro/docker-oracle6-ansible:1.9
    platform: centos
- name: oracle7-ansible-latest
  driver:
    image: rndmh3ro/docker-oracle7-ansible:latest
    platform: centos
- name: oracle7-ansible-19
  driver:
    image: rndmh3ro/docker-oracle7-ansible:1.9
    platform: centos
- name: ubuntu1204-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1204-ansible:latest
    platform: ubuntu
- name: ubuntu1204-ansible-19
  driver:
    image: rndmh3ro/docker-ubuntu1204-ansible:1.9
    platform: ubuntu
- name: ubuntu1404-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1404-ansible:latest
    platform: ubuntu
- name: ubuntu1404-ansible-19
  driver:
    image: rndmh3ro/docker-ubuntu1404-ansible:1.9
    platform: ubuntu
- name: ubuntu1604-ansible-latest
  driver:
    image: rndmh3ro/docker-ubuntu1604-ansible:latest
    platform: ubuntu
- name: ubuntu1604-ansible-19
  driver:
    image: rndmh3ro/docker-ubuntu1604-ansible:1.9
    platform: ubuntu
- name: debian7-ansible-latest
  driver:
    image: rndmh3ro/docker-debian7-ansible:latest
    platform: debian
- name: debian7-ansible-19
  driver:
    image: rndmh3ro/docker-debian7-ansible:1.9
    platform: debian
- name: debian8-ansible-latest
  driver:
    image: rndmh3ro/docker-debian8-ansible:latest
    platform: debian
- name: debian8-ansible-19
  driver:
    image: rndmh3ro/docker-debian8-ansible:1.9
    platform: debian
- name: debian9-ansible-latest
  driver:
    image: rndmh3ro/docker-debian9-ansible:latest
    platform: debian
- name: debian9-ansible-19
  driver:
    image: rndmh3ro/docker-debian9-ansible:1.9
    platform: debian


verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening

suites:
- name: os
