---
driver:
  name: docker
  use_sudo: false
  privileged: true

transport:
  max_ssh_sessions: 5

provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  hosts: all
  roles_path: ../ansible-os-hardening/
  playbook: default.yml
  ansible_extra_flags:
    - "--skip-tags=sysctl"

platforms:
- name: centos6-ansible-latest
  driver:
    image: rndmh3ro/docker-centos6-ansible:latest
    platform: centos
- name: centos6-ansible-19
  driver:
    image: rndmh3ro/docker-centos6-ansible:1.9
    platform: centos
- name: centos7-ansible-latest
  driver:
    image: rndmh3ro/docker-centos7-ansible:latest
    platform: centos
- name: centos7-ansible-19
  driver:
    image: rndmh3ro/docker-centos6-ansible:1.9
    platform: centos

verifier:
  name: inspec
  sudo: true
  inspec_tests:
    - https://github.com/dev-sec/tests-os-hardening

suites:
- name: os
